cube:
  color: brown
  created: '2025-08-26T16:47:53.990582'
  metaphor: 소화계 - 외부 정보 흡수
  name: crawling-system
  port: 8003
  purpose: 외부 데이터 수집
  type: integration-cube
  version: 1.0.0
dependencies:
  external:
  - fastapi
  - uvicorn
  - pydantic
  internal: []
interfaces:
  health_check: /health
  rest_api: /api/crawling
  websocket: /ws/crawling
performance_targets:
  cpu_utilization_pct: 70
  error_rate_pct: 0.1
  memory_limit_mb: 512
  response_time_ms: 100
