cube:
  color: yellow
  created: '2025-08-26T16:47:53.966740'
  metaphor: 신장 - 데이터 정화와 저장
  name: database-manager-system
  port: 8030
  purpose: 데이터베이스 통합 관리
  type: data-cube
  version: 1.0.0
dependencies:
  external:
  - fastapi
  - uvicorn
  - pydantic
  internal: []
interfaces:
  health_check: /health
  rest_api: /api/database-manager
  websocket: /ws/database-manager
performance_targets:
  cpu_utilization_pct: 70
  error_rate_pct: 0.1
  memory_limit_mb: 512
  response_time_ms: 100
