cube:
  color: purple
  created: '2025-08-26T16:47:53.985217'
  metaphor: 신경계 - 상태 감지
  name: performance-monitor-system
  port: 8050
  purpose: 성능 모니터링 및 메트릭
  type: monitoring-cube
  version: 1.0.0
dependencies:
  external:
  - fastapi
  - uvicorn
  - pydantic
  internal: []
interfaces:
  health_check: /health
  rest_api: /api/performance-monitor
  websocket: /ws/performance-monitor
performance_targets:
  cpu_utilization_pct: 70
  error_rate_pct: 0.1
  memory_limit_mb: 512
  response_time_ms: 100
